apiVersion: v1
kind: Secret
metadata:
  name: ms-pedidos-secret
  namespace: ms-pedidos-ns
type: Opaque
stringData:
  SERVER_PORT: "8082"
  DB_HOST: "aws-1-us-east-2.pooler.supabase.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_SSL_MODE: "require"
  DB_USER: "postgres.xxzeitbtoohxknazssdu"
  DB_PASSWORD: "Steven2005*123456-"
  PRODUCTOS_SERVICE_URL: "http://ms-productos-service.ms-productos-ns.svc.cluster.local:80"
