apiVersion: v1
kind: Service
metadata:
  name: ms-pedidos-service
  namespace: ms-pedidos-ns
spec:
  selector:
    app: ms-pedidos
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8082
  type: LoadBalancer
