apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-productos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-productos
  template:
    metadata:
      labels:
        app: ms-productos
    spec:
      containers:
      - name: ms-productos
        image: kellerr/ms-productos:v1 
        ports:
        - containerPort: 8081
        env:
        - name: SERVER_PORT
          value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-productos-service
spec:
  selector:
    app: ms-productos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP
