server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ms-productos

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:aws-1-us-east-2.pooler.supabase.com}:${DB_PORT:5432}/${DB_NAME:postgres}?sslMode=${DB_SSL_MODE:require}&preparedStatementCacheQueries=0
    username: ${DB_USER:postgres.xxzeitbtoohxknazssdu}
    password: ${DB_PASSWORD:Steven2005*123456-}
    pool:
      initial-size: 2
      max-size: 5