apiVersion: v1
kind: Secret
metadata:
  name: ms-productos-secret
  namespace: ms-productos-ns
type: Opaque
stringData:
  SERVER_PORT: "8081"
  DB_HOST: "aws-1-us-east-2.pooler.supabase.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_SSL_MODE: "require"
  DB_USER: "postgres.xxzeitbtoohxknazssdu"
  DB_PASSWORD: "Steven2005*123456-"
